import Head from 'next/head'
import Image from 'next/image'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import {useQuery, gql} from '@apollo/client';
import styles from '../styles/Home.module.css'

const GET_MY_TOOLS = gql`
{
     myTools{
         tools{
          id,
          description
         }
         message,
         errorCode
       }
}
`

export default function Home() {

  const {loading, error, data} = useQuery(GET_MY_TOOLS);
  if(loading){
    return "loading";
  }
  if(error){
    return "error";
  }
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <TextField
              margin="normal"
              required
              fullWidth
              id="email"
              label="Email Address"
              name="email"
              autoComplete="email"
              autoFocus
            />
            <TextField
              margin="normal"
              required
              fullWidth
              name="password"
              label="Password"
              type="password"
              id="password"
              autoComplete="current-password"
            />
            <Button
              type="submit"
              fullWidth
              variant="contained"
              sx={{ mt: 3, mb: 2 }}
            >
              Sign In
            </Button>
      </div>

      
    </div>
  )
}
