import Head from 'next/head'
import Image from 'next/image'
import {useQuery, gql} from '@apollo/client';
import Router from 'next/router'
import styles from '../styles/Home.module.css'

const GET_MY_TOOLS = gql`
{
     myTools{
         tools{
          id,
          description
         }
         message,
         errorCode
       }
}
`

export default function Home() {

  const token = typeof window !== "undefined" && localStorage.getItem('accessToken')?localStorage.getItem('accessToken'): "";
  if(typeof window !== "undefined" && !token){
    Router.push('/login')
  }
  
  const {loading, error, data} = useQuery(GET_MY_TOOLS, {
    context: {
        headers: {
            "Authorization": "Bearer " + token
        }
    }
});
  if(loading){
    return "loading";
  }
  if(error){
    return "error";
  }
  console.log(data);

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      
    </div>
  )
}
